name: SMRP
version: 1.0.0
config-version: 2
profile: SMRP
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  SMRP:
    +materialized: view
